services: 
  # web server
  nginx: 
    container_name: ${CONTAINER_NAME}-nginx
    image: nginx:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:80" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
      - wordpress:/var/www/html
    networks:
      - fall

  # database
  database:
    container_name: ${CONTAINER_NAME}-database
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 5s
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - fall

  #phpmyadmin
  phpmyadmin:
    container_name: ${CONTAINER_NAME}-phpmyadmin
    image: phpmyadmin/phpmyadmin
    env_file: .env
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
    ports:
      - "8081:80"
    networks:
      - fall

  # wordpress
  wordpress: 
    depends_on:
      - database
    container_name: ${CONTAINER_NAME}-wordpress
    image: wordpress:6.5.2-fpm-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: '${DATABASE_USER}'
      WORDPRESS_DB_PASSWORD: '${DATABASE_PASSWORD}'
      WORDPRESS_DB_NAME: '${DATABASE_NAME}'
    volumes:
      - wordpress:/var/www/html
    networks:
      - fall

volumes:
  db_data:
  wordpress:

networks:
  fall:
    driver: bridge